source:     ./_content
safe:        false
baseurl:    /
exclude:     [_app, config.ru]
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
paginate:     5
paginate_path: "news/page-:num"
flickr:
  api_key: 06a5a0dfe07d9d2d0af5ae6fe74bad03
permalink: pretty
