source:      ./_content
safe:        false
plugins:     ./_plugins
baseurl:     /
url:         http://hikr.jp
exclude:     [_app, config.ru]
destination: ./_site
layouts:     ./_layouts
future:      true
lsi:         false
markdown:    redcarpet
paginate:     5
paginate_path: "news/page-:num"
flickr:
  api_key: 06a5a0dfe07d9d2d0af5ae6fe74bad03
# permalink: pretty
