safe:        true
auto:        true
baseurl:    /
# url: http://guide.hikr.jp
destination: ./_site
plugins:     ./_plugins
future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   /:year-:month-:day/:title.html
categories:
 - Chichibu
 - Okutama
 - Tanzawa
