source 'https://rubygems.org'
ruby '1.9.3'
gem 'sinatra'
gem 'haml'
gem 'nokogiri'
gem 'liquid', '>=2.5.3'
gem 'redcarpet', '=2.2.2'
gem 'typhoeus'
gem 'fleakr', :git => "git://github.com/rfc2616/fleakr.git"
gem 'jekyll-less'
gem 'therubyracer'
#gem 'rack-jekyll'
