source 'https://rubygems.org'
gem 'github-pages'
ruby '1.9.3'
gem 'sinatra'
gem 'haml'
gem 'nokogiri'
gem 'typhoeus'
gem 'fleakr', :git => "git://github.com/rfc2616/fleakr.git"
gem 'jekyll-less'
gem 'therubyracer'
gem 'rack-jekyll'
